language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: fZDqV9dOcoduJNx83zEA3H9HF0CqWv0yWHCkPOh/fyLoN6OWhwUGDM8AUi/zq5ZJQQ6kwyUHr2ZwZ9DJrAJ7Dm7s1KRWNIfsat5A9QruxejG+O1DM+1CW5rVTrpMUytNmPtj/FXjMrrvp8ZXGpk658qR9lcyIQwd5XBDqPW67ntyqV4nXqhOBZAPQOvmdgSd6Jt3zufaVEOZh6UHyy4b70CZTJaAmQfoJiBP+Oq440qa75HKyQtPG9wNcr8lWQhqQE6MrTceBAAzIzRPUI2sQNkCe3X0Ob19SoynlC2sQI6+CWUBpl4l6U7ebiRPVhgxI+0zOjLCaRzxKTVDJ415pZGkls75kE9Pky4Z3XfsrDIka//ocx4R9ZdY9mw75r8CbnvjU6/YSxnByF20L/D+Sgwn0x94IAOsD7czt+f7u7BKqSZEyxYZLQFBem8W2g8SY1c+aVBHrTjuIM1ShG4Ba4nPpdBNS5A7jjEbepGw2K0JyIddrrlhp19dLiiL3QnYZxorWc5Qzv3a3LX2JQYQQHZmGRxsvipT8TZXmHYHEkZQXRFOGKPHc6OfvuZUMFpMG8HuiBuVJyzdjwAOaeK56LhAqFrDI1suGb4jJjX7YlRd3z3WCwT3BKYdz5XRt/NdQOu1pKPbYFsmxU7QVh2hudem0UjVm/I14n9CWKjrWVY=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
