language: r
warnings_are_errors: true
sudo: false
cache: packages
os:
- linux
- osx
r_check_args: "--as-cran --install-args=--build"
after_success:
- Rscript -e 'covr::coveralls(type = "all")'
- Rscript -e 'covr::codecov(type = "all")'
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: fslr*.t*gz
  on:
    tags: true
    repo: muschellij2/fslr
  api-key:
    secure: Jm+3oSdVcW2J1jzT6oGic5d8bVFlBWP3eEqWn3G4ZcFAVLuw1ZXLN47UmNr5u4G0Kn1Tf89c8OZbJUkpArumgviAuOHRyfu64QaQqaOsrHbYrnrq74/SvcD6T7PxKw2b8XVloJHLJMFqVTwAdyQIB2yUnfujW+5lWPyf8+cnJ1SpR7UDH0/pYdszbuaqs28ICe5/7sHgIUuds9zlzpbjKhRYw8wMngSBcq1wAFzPDRETWyUo786SHkGaYT/CJTHfgL7BZnkGoRPS2Qy8rgLFXLk6eKA2npC+evsfiyvVhUeOVXNSd3EeUcGbyOqwcks4XamSuMNRHWSYdWloc4tXtECBv6tOiHZR7WnYEbw326S0t43rJ0k7+50GvQpCRF6PosI0fvjeNSc0y773XF1lu7rKNlOpqnnnAuYrVl1iSNG0ur69WQI8d70DEHGtwpZekjgNfigLN65NqtIYROYLARE69F6AQq5OqbUFiGBsEIcYZH81MIXxHre1RvYmbQeKCRuWtISZgnFkwTxRMnE0pmaWzXhfxZW2xbAG+9/etut0wYyIcDOtAayueIWxqeI43IBT0ORvidmUDxS4KLNZfsDn1mRCDGDmzeIkPTzwigroiD/MZ1ISLRXqE8U0xXruzKEcs3qYJPgSf0QHBpHDgrkLDBVwZq4zV/zuG8g3bv0=
