language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: mikJesrZ0vSby4ljiVbQVSKSqyDC/fkbypkYgFm/r2Jh6kLZzxTmJjggVpEB0ByVVWt4Tzy9b23MX4siycNZsOlDL7tNqKKttjCouX/4XOHud8AO07q/WQCLDC7HW1ymPlX1E+nsObjD96zAe8pcCor21O2BB1jOW0p0DV35tAdzqWvD0VS7GEVcXlpEresH2VQ9X4JvJK8pnNGB+7++AOOYmu6SnO2wKFFecfXKLhoEaLHHY6rJ6L1crTs00IAEUkYv9LZV5YYYhvI73vpGsQw020W3wBjeYlSarER89lwLsi1tUUjDvy5AbUb4aHOzksHgQ5viYVylyA8h8zClcawBSN5woIMffB/rBR5Xz4ETVLDKd+IsnVChe/HKYrDFEWoINmtiJsOVt5ke/cvr1nRmjGsHfnSxn8t+avx11FIjZVSdoJ6kwfyd+5E9nVZAyx5X1V3PHGq9jGZ4EmvDDNzdTydhRqp2cVPC0PSMETtQxk2U44p9wQG7Y4LWQAwwUtMG8W0b1jEXVMtgW7ZOdraJX5+VhIeyoM1W/qCgcW/OYZVjN3NCRDRHrE9F4a1/rZoKBBRJqEmtg+2krGb+gnSnMrwMcFMghV43llUVZF8tV61+aQgNnBzba4botkagLLSSRO2WG6cvSRn5qhr+xd2EMiQ3GKZBrYJpq6fM5bA=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
