language: r
warnings_are_errors: true
sudo: false
cache: packages
os:
- linux
- osx
r_check_args: "--as-cran --install-args=--build"
after_success:
- Rscript -e 'covr::coveralls(type = "all")'
- Rscript -e 'covr::codecov(type = "all")'
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: fslr*.t*gz
  on:
    tags: true
    repo: muschellij2/fslr
  api-key:
    secure: SOPNhDqlV76nlr7rzmXPfnR1lJVrSOjxGNm53ROThynckSlM44QozGMhw84knKK1gn73GRIMAjDDVYVdvdcFSgXVU4Q9RXl//Rbdp7oS+2njGpxz6I3PwQ2VBr+nK7QzGHpa6cDV6xIdwd0uAiYHbk/Js4FMNnqF2iyE8UOfAXJBp/6dfwy2e/Gg05UFgYGgCCcuKJZgRoDW2+IExk8bTwMfI/xuLe7GCznOCn5rlG4sZ0JuMXyLN7tJZFSzOVQv/XjTwHBzon6HlhQd2XrKpvA44Acgb11ConoBc9lj8g66TXq75dX/O+qBCuMkuq49AR+fE9Az+Ww7c3JT/dn9EsxCWVsyHQyjC7YuuW3njjTNowwS2uoeCOh2fOrQdZeum2oja9O+QO47DL9CBVvPPEfstZ+FU1VNYBzrhQYpJ2CV9Xez+pleSEIzONpZPitgd55UsttPFOvGNBI8XpKWZ2GnZECakktHz3u/FGwxtIcBcJYPnS3UWQ/gdZJ9IHEJDHZrhlSAcQ5A1DFHkWJCnV/rhDNWbe88LkjnrfjeeIW9ZMenp3kzUhPnM5Ych6j1n9YoHHyYBCQexm/sw6Ef6u0ognIQzoHGwh9OozQrYgyg5AkZmcZ+lJcoSnTkfGL5w+w5Mo3wWuxA18em115j8qmJqQYPs7JzBQyRt+NxOXM=
