language: r
warnings_are_errors: true
sudo: false
cache: packages
os:
- linux
- osx
r_check_args: "--as-cran --install-args=--build"
after_success:
- Rscript -e 'covr::coveralls(type = "all")'
- Rscript -e 'covr::codecov(type = "all")'
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: fslr*.t*gz
  on:
    tags: true
    repo: muschellij2/fslr
  api-key:
    secure: RenSwfT1fAMNDRTwxoCu+LMXbua09HXvukAalcWvtyNa3wkLXsHS9dd5G561ngB2/MRsST1p56XTr8DKno93RlnTL8MwOQX9Q2xoVCtbFWPtXsE3119bUemhojORzGVbzqG6lwuw1wwoTa8YPrVNttuKb5E7Oi2MjbMa0v788MAxIBPTYjU2pXdwRAnB/9sy7GueOhHbPlIBE/UPtBVKJ2rhwDMy7aaELV7nEgORv58p4SztNYCj9oQwfyucVrNNZPDUDmNMbiLjFYWAQq0LmVONL2AOlkCG7pJiPLl3k3E4XyqKIMSAJqpUJ4iaZAevJM9E4kChloE375DSI6mPtYVgPShQ9vPLgJyM+PQ+yABdc3X+ff+qvdJGgE2h8dySqbmN42Mc2sIRBvPv+EC7isTMUxUIlD/BRYUacX3bmW1wtAZSs6LwkTx8n6vqTMjuQ5adt6E9rm3ZS9m/EVAwxJZO0v6ufie9zPvEVMh23dZRh2eWrRuwmxwxpHyuzrutUcPAiyaEdxjH4CrGP4+RhaAZQi8i117hBa7yse4YFnMwCJ6f84jFnVYTKhAV32QfkdNm9q19XusRc63dSGTWZ58+ZcXoCIkSGPnBUgoPnRJJds+hJwrdkTLuzDPQoj1TKzdI+j2GGVfl7R/zGVsYkMv0l1jULGv79K6N4XRXRjI=
